effects:
  'donate':
    regionTypeId: 'donate'
    list:
      '0':
        type: INVISIBILITY
        duration: 999999
        amplifier: 2
        ambient: true
        particle: true
      '1':
        type: FAST_DIGGING
        duration: 99999
        amplifier: 2
        ambient: true
        particle: true