tnts:
  'sheptun':
    corners:
      enable: false
      material: AIR
    fire:
      enable: false
      radius: 0
      ticks: 0
    explosion:
      yield: 4
      setGlowing: false
      fuseTicks: 40
      damaged: 0
    item:
      name: "&fШептун"
      lore: []
  'molotov':
    corners:
      enable: false
      material: LAVA
    fire:
      enable: true
      radius: 10
      ticks: 200
    explosion:
      yield: 10
      setGlowing: false
      fuseTicks: 40
      damaged: 0
    item:
      name: "&fМолотов"
      lore: []
  'k-12':
    corners:
      enable: false
      material: LAVA
    fire:
      enable: false
      radius: 0
      ticks: 0
    explosion:
      yield: 4
      setGlowing: false
      fuseTicks: 40
      damaged: 1
    item:
      name: "&fК-12"
      lore: []
