name: Maven Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Необходимо для работы с тегами

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn -B clean package

      - name: Publish to GitHub Packages
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create git tag
        run: |
          git config --global user.name "Loft69"
          git config --global user.email "animesenpai.kimi@gmail.com"
          git tag -a v$NEW_VERSION -m "Release $NEW_VERSION"
          git push origin v$NEW_VERSION